server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/career?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
#    password: hxf.20210611
    password: Wa2497686061
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      # 最大支持文件大小
      max-file-size: 100MB
      # 最大支持请求大小
      max-request-size: 100MB
  data:
    redis:
#      cluster:
#        nodes:
#          - 192.168.252.128:7001
#          - 192.168.252.128:7002
#          - 192.168.252.128:7003
#          - 192.168.252.128:8001
#          - 192.168.252.128:8002
#          - 192.168.252.128:8003
#      host: 127.0.0.1
      host: 47.99.156.111
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
  cache:
    type: redis
    redis:
      time-to-live: 60
xf:
  config:
    hostUrl: https://spark-api.xf-yun.com/v3.5/chat
    appId: 5483859a
    apiSecret: YjAwMjljMzQ0ZjY1ODJkYTMxMWViOTA5
    apiKey: 3687edcd553f58ab30970f74ccc613f8
    maxResponseTime: 999999999

qingstor:
  access_key_id: KCSIUHLLRMAKEZDRPMKT
  secret_access_key: t7czuPBCS5ALhynW86LFpWVIRZDOLuAN0NZqnSPZ
  endpoint: https://qingstor.com
  enable_virtual_host_style: false
  cname_support: false
  read_timeout: 100
  connection_timeout: 60
  write_timeout: 100

hutool:
  AES_KEY: F&U#7r@]E{Dx9sRvX!P3^GcW@2]H*+A~
