server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/career?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: hxf.20210611
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      # 最大支持文件大小
      max-file-size: 100MB
      # 最大支持请求大小
      max-request-size: 100MB
resume:
  upload:
    # 简历保存路径
    directory: D:/resume/
