server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/career?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: hxf.20210611
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update